import logging
import aiohttp
import asyncio
import time
from datetime import datetime
from collections import defaultdict
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup, ReplyKeyboardMarkup, KeyboardButton
from telegram.constants import ChatAction, ParseMode
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes, CallbackQueryHandler

# --- CONFIG & SECURITY ---
TELEGRAM_TOKEN = "8486840944:AAHPzM7-U3r3m3F_fQXr-4nrHqZE2GpeFfk"  # Replace with actual token
VERSION = "3.0.1 (Premium Gold)"

# Logging Configuration
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)
logger = logging.getLogger(__name__)

# Memory and Stats
user_memory = defaultdict(list)
user_stats = defaultdict(lambda: {"joined": datetime.now(), "requests": 0})

# --- STYLING CONSTANTS ---
HEADER = "💎 **SAEID ALPHA AI | PREMIUM** 💎\n"
LINE = "━━━━━━━━━━━━━━━━━━━━\n"

# --- CORE FUNCTIONS ---

async def get_ai_response(user_id: int, user_name: str, user_text: str, mode: str="Professional"):
    """Enhanced AI interaction with retry logic and personality."""
    memory = user_memory[user_id][-8:]
    system_prompt = (
        f"You are Saeid Alpha AI 👑, a world-class assistant. "
        f"User: {user_name}. Mode: {mode}. Be concise, intelligent, and helpful."
    )
    
    payload = {
        "messages": [{"role": "system", "content": system_prompt}] + memory + [{"role": "user", "content": user_text}]
    }

    async with aiohttp.ClientSession() as session:
        for attempt in range(2): # Try twice
            try:
                async with session.post("https://mn-chat-bot-api.vercel.app/chat", json=payload, timeout=25) as resp:
                    if resp.status == 200:
                        data = await resp.json()
                        return data.get("response", "Internal Error.")
            except Exception as e:
                if attempt == 1: return "❌ সার্ভার এখন ওভারলোডেড। একটু পর চেষ্টা করুন।"
                await asyncio.sleep(1)

# --- TELEGRAM COMMANDS ---

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    user_stats[user.id]["requests"] += 1
    
    # Custom Keyboard for fast access
    kb = [
        [KeyboardButton("🎨 Generate Image"), KeyboardButton("🎭 Create Meme")],
        [KeyboardButton("📝 Story Mode"), KeyboardButton("👤 Profile")]
    ]
    reply_markup = ReplyKeyboardMarkup(kb, resize_keyboard=True)

    welcome_msg = (
        f"{HEADER}{LINE}"
        f"স্বাগতম, **{user.first_name}**! 👑\n\n"
        f"আমি একটি মেমরি-এনহ্যান্সড এআই। আপনি আমার সাথে চ্যাট করতে পারেন, "
        f"ছবি বা মিম তৈরি করতে পারেন।\n\n"
        f"👇 নিচের মেনু থেকে অপশন সিলেক্ট করুন।"
    )
    
    await update.message.reply_text(welcome_msg, reply_markup=reply_markup, parse_mode=ParseMode.MARKDOWN)

async def profile_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    stats = user_stats[user.id]
    profile_text = (
        f"{HEADER}{LINE}"
        f"👤 **User:** {user.first_name}\n"
        f"🆔 **ID:** `{user.id}`\n"
        f"📊 **Requests:** {stats['requests']}\n"
        f"📅 **Member Since:** {stats['joined'].strftime('%Y-%m-%d')}\n"
        f"🌟 **Status:** Premium Member"
    )
    await update.message.reply_text(profile_text, parse_mode=ParseMode.MARKDOWN)

# --- ENHANCED MEDIA HANDLERS ---

async def media_flow(update: Update, prompt: str, api_url: str, media_type: str):
    """Generic flow for Image, Meme, GIF to avoid code repetition."""
    status_msg = await update.message.reply_text(f"✨ `{media_type}` তৈরির কাজ চলছে, অপেক্ষা করুন...")
    
    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(api_url, json={"prompt": prompt}) as resp:
                data = await resp.json()
                file_url = data.get(f"{media_type.lower()}_url")
                
                if file_url:
                    await update.message.chat.send_action(ChatAction.UPLOAD_PHOTO)
                    if media_type == "GIF":
                        await update.message.reply_animation(file_url, caption=f"✅ {prompt}")
                    else:
                        await update.message.reply_photo(file_url, caption=f"✨ Generated by Saeid Alpha AI")
                    await status_msg.delete()
                else:
                    await status_msg.edit_text("❌ দুঃখিত, জেনারেট করা সম্ভব হয়নি।")
    except:
        await status_msg.edit_text("⚠️ এপিআই এরর! পরে চেষ্টা করুন।")

# --- MESSAGE LOGIC ---

async def handle_text(update: Update, context: ContextTypes.DEFAULT_TYPE):
    text = update.message.text
    user = update.effective_user
    user_stats[user.id]["requests"] += 1

    # Route buttons to functions
    if text == "🎨 Generate Image":
        return await update.message.reply_text("🖼 ছবি বানাতে লিখুন: `/image your_prompt`", parse_mode=ParseMode.MARKDOWN)
    if text == "👤 Profile":
        return await profile_handler(update, context)
    if text == "🎭 Create Meme":
        return await update.message.reply_text("🎭 মিম বানাতে লিখুন: `/meme text`", parse_mode=ParseMode.MARKDOWN)

    # General AI Chat
    await update.message.chat.send_action(ChatAction.TYPING)
    reply = await get_ai_response(user.id, user.first_name, text)
    
    # Update memory
    user_memory[user.id].append({"role": "user", "content": text})
    user_memory[user.id].append({"role": "assistant", "content": reply})
    
    await update.message.reply_text(f"👑 **Saeid Alpha:**\n\n{reply}", parse_mode=ParseMode.MARKDOWN)

# --- MAIN SETUP ---

def main():
    # Build Application
    app = Application.builder().token(TELEGRAM_TOKEN).build()

    # Add Command Handlers
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("profile", profile_handler))
    
    # Support for /image, /meme as before
    app.add_handler(CommandHandler("image", lambda u, c: media_flow(u, " ".join(c.args), "https://mn-chat-bot-api.vercel.app/image", "Image") if c.args else u.message.reply_text("Prompt দিন!")))
    app.add_handler(CommandHandler("meme", lambda u, c: media_flow(u, " ".join(c.args), "https://mn-chat-bot-api.vercel.app/meme", "Meme") if c.args else u.message.reply_text("Prompt দিন!")))

    # Text Handler
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_text))

    print(f"--- Saeid Alpha AI {VERSION} is Live ---")
    app.run_polling()

if __name__ == "__main__":
    main()
