import logging
import requests
import time
from telegram import Update, constants, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes

# --- কনফিগারেশন ---
TELEGRAM_TOKEN = '8515258058:AAG-QCqbpo1UvjRahnW9oLnb5TGbp2GG34A'
CHAT_API_URL = "https://mn-chat-bot-api.vercel.app/chat"
IMAGE_API_URL = "https://image.pollinations.ai/prompt/"

# লগিং সেটআপ
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)

# --- AI রেসপন্স ফাংশন (Chat & Coding) ---
def get_ai_chat_response(user_text):
    payload = {
        "messages": [
            {
                "role": "system", 
                "content": "Your name is Saeid Alpha AI 👑. You are a high-end, professional AI developer. You provide expert solutions in coding, technology, and general knowledge. Always be polite and helpful."
            },
            {"role": "user", "content": user_text}
        ]
    }
    try:
        response = requests.post(CHAT_API_URL, json=payload, timeout=45)
        data = response.json()
        return data.get('response') or data.get('content') or "I am processing your request. Please wait."
    except Exception as e:
        return f"System Error: {str(e)}"

# --- স্টার্ট কমান্ড (/start) ---
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    welcome_text = (
        f"👋 **Greetings, {user.first_name}!**\n\n"
        f"Welcome to **Saeid Alpha AI 👑** — the most advanced terminal-based AI assistant.\n\n"
        f"✨ **Capabilities:**\n"
        f"🚀 **High-Speed Coding:** Ask me to write or debug any code.\n"
        f"🖼 **AI Image Gen:** Use `/img` to create realistic art.\n"
        f"🧠 **Knowledge:** Expert-level chat on any topic.\n\n"
        f"💡 **Example:** `/img a cyberpunk warrior in Dhaka`"
    )
    
    # প্রফেশনাল বাটন
    keyboard = [
        [InlineKeyboardButton("Developer 👨‍💻", url="https://t.me/saeid9_90")],
        [InlineKeyboardButton("Project Updates 📢", url="https://t.me/saeid9_90")]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)

    await update.message.reply_text(
        welcome_text, 
        parse_mode=constants.ParseMode.MARKDOWN,
        reply_markup=reply_markup
    )

# --- ইমেজ জেনারেশন কমান্ড (/img) ---
async def generate_image(update: Update, context: ContextTypes.DEFAULT_TYPE):
    prompt = " ".join(context.args)
    if not prompt:
        await update.message.reply_text("⚠️ **Usage:** `/img [your visual description]`")
        return

    msg = await update.message.reply_text("🎨 **Saeid Alpha AI** is painting your imagination... Please wait.")
    
    # URL এনকোডিং
    encoded_prompt = requests.utils.quote(prompt)
    image_url = f"{IMAGE_API_URL}{encoded_prompt}?width=1024&height=1024&model=flux"
    
    try:
        await update.message.reply_chat_action(action=constants.ChatAction.UPLOAD_PHOTO)
        await update.message.reply_photo(
            photo=image_url, 
            caption=f"✅ **Generated by Saeid Alpha AI 👑**\n📌 **Prompt:** {prompt}",
            parse_mode=constants.ParseMode.MARKDOWN
        )
        await msg.delete()
    except Exception:
        await msg.edit_text("❌ Failed to generate image. Please try a different prompt.")

# --- স্মার্ট মেসেজ হ্যান্ডলার ---
async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_text = update.message.text
    if not user_text: return

    # টাইপিং ইন্ডিকেটর
    await update.message.reply_chat_action(action=constants.ChatAction.TYPING)
    
    response = get_ai_chat_response(user_text)
    
    # প্রফেশনাল ফরম্যাটিং
    if "```" in response:
        await update.message.reply_text(response, parse_mode=constants.ParseMode.MARKDOWN)
    else:
        await update.message.reply_text(response)

# --- রানার ---
if __name__ == '__main__':
    application = Application.builder().token(TELEGRAM_TOKEN).build()
    
    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("img", generate_image))
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))
    
    print("Saeid Alpha AI 👑 is now Deployed & Live!")
    application.run_polling()
